apiVersion: platform.example.com/v1alpha1
kind: XStorageBucket
metadata:
  name: example-kcl
spec:
  compositionSelector:
    matchLabels:
      language: kcl
  parameters:
    location: US
    versioning: true
    acl: publicRead
